### ISSUE TITLE
Test custom post types and taxonomies

### ISSUE THREAD

**Issue by marpa** [clas-web/multisite-csv-importer#8]
Add, remove and replace categories, tags and custom taxonomy terms.  Should be able to include tags, categories and custom taxonomy terms in csv file.  Terms should be comma-separated.

if action = add, than add terms specified
if action = remove, than remove terms specified
if action = replace, than replace existing terms with new ones specified

**Comment by atrus1701** [comment]
This repository is no longer in user.  See Organization Hub.
